// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skillitory.Api.DataStore;

#nullable disable

namespace Skillitory.Api.DataStore.Migrations
{
    [DbContext(typeof(SkillitoryDbContext))]
    partial class SkillitoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claim");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claim_role_id");

                    b.ToTable("role_claim", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claim");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claim_user_id");

                    b.ToTable("user_claim", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_login");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_login_user_id");

                    b.ToTable("user_login", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.ToTable("user_role", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_token");

                    b.ToTable("user_token", "auth");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Audit.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditLogTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("audit_log_type_id");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_stamp");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("AuditLogTypeId")
                        .HasDatabaseName("ix_audit_log_audit_log_type_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_log_user_id");

                    b.ToTable("audit_log", "audit");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Audit.AuditLogMetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditLogId")
                        .HasColumnType("integer")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_data");

                    b.HasKey("Id")
                        .HasName("pk_audit_log_metadata");

                    b.HasIndex("AuditLogId")
                        .HasDatabaseName("ix_audit_log_metadata_audit_log_id");

                    b.ToTable("audit_log_metadata", "audit");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Audit.AuditLogType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_audit_log_type");

                    b.ToTable("audit_log_type", "audit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SignIn"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SignOut"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ForgotPassword"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ResetPassword"
                        },
                        new
                        {
                            Id = 5,
                            Name = "NewUserRegistered"
                        },
                        new
                        {
                            Id = 6,
                            Name = "NewUserEmailVerified"
                        });
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Auth.AuthRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsApplicationAdministratorRole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_application_administrator_role");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("role", "auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "5978c351-c872-4e36-a64e-b3526cade363",
                            Description = "Users in this role can read and write all Skillitory resources, including customer data.",
                            IsApplicationAdministratorRole = true,
                            Name = "Skillitory Administrator",
                            NormalizedName = "SKILLITORY ADMINISTRATOR"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "cb397c9c-2c33-47a7-9f38-f7acb5879f4b",
                            Description = "Users in this role can read all Skillitory resources, including customer data.",
                            IsApplicationAdministratorRole = true,
                            Name = "Skillitory Viewer",
                            NormalizedName = "SKILLITORY VIEWER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "7d6418e6-c7f6-41d9-aa0e-7e83cba4dfa0",
                            Description = "Users in this role can administrate the organizations that they're associated with.",
                            IsApplicationAdministratorRole = false,
                            Name = "Organization Administrator",
                            NormalizedName = "ORGANIZATION ADMINISTRATOR"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "8898d64c-8a2d-4d2e-acd7-15630b419469",
                            Description = "Users in this role can view the details and users of the organizations that they're associated with.",
                            IsApplicationAdministratorRole = false,
                            Name = "Organization Viewer",
                            NormalizedName = "ORGANIZATION VIEWER"
                        },
                        new
                        {
                            Id = 5,
                            ConcurrencyStamp = "456b24f8-a56d-4fa3-a4e6-fa0d63601488",
                            Description = "Users in this role are standard users that can manage their own profile, skills, goals, etc.",
                            IsApplicationAdministratorRole = false,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Auth.AuthUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsSignInAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sign_in_allowed");

                    b.Property<bool>("IsSystemUser")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_user");

                    b.Property<DateTimeOffset>("LastPasswordChangedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_password_changed_date_time");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<int?>("OtpTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("otp_type_id");

                    b.Property<DateTimeOffset>("PasswordExpirationDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_expiration_date_time");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<DateTimeOffset?>("TerminatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminated_on");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date_time");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserUniqueKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_unique_key");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OtpTypeId")
                        .HasDatabaseName("ix_user_otp_type_id");

                    b.HasIndex("UserUniqueKey")
                        .IsUnique()
                        .HasDatabaseName("ix_user_user_unique_key");

                    b.ToTable("user", "auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a4b3e319-75dd-4fca-a187-3ad9b68f4b94",
                            CreatedBy = 1,
                            CreatedDateTime = new DateTimeOffset(new DateTime(2024, 9, 14, 20, 20, 13, 198, DateTimeKind.Unspecified).AddTicks(1740), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "system_user@skillitory.com",
                            EmailConfirmed = false,
                            IsSignInAllowed = false,
                            IsSystemUser = true,
                            LastPasswordChangedDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LockoutEnabled = false,
                            NormalizedEmail = "SYSTEM_USER@SKILLITORY.COM",
                            NormalizedUserName = "SYSTEM_USER@SKILLITORY.COM",
                            PasswordExpirationDateTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NEVER_GOING_TO_SIGN_IN",
                            TwoFactorEnabled = false,
                            UserName = "system_user@skillitory.com",
                            UserUniqueKey = "h9sj1uho8609n46dhxq3zv7c"
                        });
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Auth.OtpType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_otp_type");

                    b.ToTable("otp_type", "auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Email"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TimeBased"
                        });
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Auth.PasswordHistory", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.HasKey("UserId", "PasswordHash")
                        .HasName("pk_password_history");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_history_user_id");

                    b.ToTable("password_history", "auth");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Auth.UserRefreshToken", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("jti");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<DateTimeOffset>("ExpirationDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date_time");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Jti")
                        .HasName("pk_user_refresh_token");

                    b.HasIndex("UserId", "Jti")
                        .IsUnique()
                        .HasDatabaseName("ix_user_refresh_token_user_id_jti");

                    b.HasIndex("UserId", "Token")
                        .IsUnique()
                        .HasDatabaseName("ix_user_refresh_token_user_id_token");

                    b.ToTable("user_refresh_token", "auth");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Mbr.Member", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("AvatarStoredFileId")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_stored_file_id");

                    b.Property<string>("Biography")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("biography");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Education")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("education");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("integer")
                        .HasColumnName("supervisor_id");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date_time");

                    b.HasKey("UserId")
                        .HasName("pk_member");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_member_department_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_member_organization_id");

                    b.HasIndex("SupervisorId")
                        .HasDatabaseName("ix_member_supervisor_id");

                    b.ToTable("member", "mbr");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Org.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("DepartmentUniqueKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_unique_key");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("LogoStoredFileId")
                        .HasColumnType("integer")
                        .HasColumnName("logo_stored_file_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date_time");

                    b.HasKey("DepartmentId")
                        .HasName("pk_department");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_department_created_by");

                    b.HasIndex("DepartmentUniqueKey")
                        .IsUnique()
                        .HasDatabaseName("ix_department_department_unique_key");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_department_updated_by");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_department_organization_id_name");

                    b.ToTable("department", "org");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Org.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrganizationId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalIdName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id_name");

                    b.Property<bool>("IsLogoOverrideAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_logo_override_allowed");

                    b.Property<bool>("IsSystemOrganization")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_organization");

                    b.Property<int?>("LogoStoredFileId")
                        .HasColumnType("integer")
                        .HasColumnName("logo_stored_file_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("OrganizationUniqueKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("organization_unique_key");

                    b.Property<int?>("PasswordLifetimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("password_lifetime_days");

                    b.Property<int?>("PreviousTrackedPasswordCount")
                        .HasColumnType("integer")
                        .HasColumnName("previous_tracked_password_count");

                    b.Property<DateOnly?>("TrialPeriodEndsOn")
                        .HasColumnType("date")
                        .HasColumnName("trial_period_ends_on");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date_time");

                    b.HasKey("OrganizationId")
                        .HasName("pk_organization");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_organization_created_by");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_name");

                    b.HasIndex("OrganizationUniqueKey")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_organization_unique_key");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_organization_updated_by");

                    b.ToTable("organization", "org");

                    b.HasData(
                        new
                        {
                            OrganizationId = 1,
                            CreatedBy = 1,
                            CreatedDateTime = new DateTimeOffset(new DateTime(2024, 9, 14, 20, 20, 13, 198, DateTimeKind.Unspecified).AddTicks(2000), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "The organization that owns and developed Skillitory.",
                            IsLogoOverrideAllowed = false,
                            IsSystemOrganization = true,
                            Name = "StaticSphere",
                            OrganizationUniqueKey = "oapgxnjraoho84o8rryjsbxa"
                        });
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Org.OrganizationChurn", b =>
                {
                    b.Property<int>("OrganizationChurnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("organization_churn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrganizationChurnId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("details");

                    b.Property<bool>("IsChurned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_churned");

                    b.Property<int>("OrganizationChurnCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_churn_category_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date_time");

                    b.HasKey("OrganizationChurnId")
                        .HasName("pk_organization_churn");

                    b.HasIndex("OrganizationChurnCategoryId")
                        .HasDatabaseName("ix_organization_churn_organization_churn_category_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_churn_organization_id");

                    b.ToTable("organization_churn", "org");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Org.OrganizationChurnCategory", b =>
                {
                    b.Property<int>("OrganizationChurnCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("organization_churn_category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrganizationChurnCategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("OrganizationChurnCategoryId")
                        .HasName("pk_organization_churn_category");

                    b.ToTable("organization_churn_category", "org");

                    b.HasData(
                        new
                        {
                            OrganizationChurnCategoryId = 1,
                            Description = "The user has churned because they were unhappy with some element of the application.",
                            Name = "Unhappy with Application"
                        },
                        new
                        {
                            OrganizationChurnCategoryId = 2,
                            Description = "The user has churned because they were unhappy with service.",
                            Name = "Unhappy with Service"
                        },
                        new
                        {
                            OrganizationChurnCategoryId = 3,
                            Description = "The user has churned because they no longer feel that the product is cost effective.",
                            Name = "No Longer Price Effective"
                        },
                        new
                        {
                            OrganizationChurnCategoryId = 4,
                            Description = "The user has churned for a reason other than that provided by the other churn options.",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claim_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claim_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_login_user_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_role_id");

                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_token_user_user_id");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Audit.AuditLog", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Audit.AuditLogType", "AuditLogType")
                        .WithMany()
                        .HasForeignKey("AuditLogTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_audit_log_types_audit_log_type_id");

                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_asp_net_users_user_id");

                    b.Navigation("AuditLogType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Audit.AuditLogMetaData", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Audit.AuditLog", "AuditLog")
                        .WithMany()
                        .HasForeignKey("AuditLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_metadata_audit_log_audit_log_id");

                    b.Navigation("AuditLog");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Auth.AuthUser", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.OtpType", "OtpType")
                        .WithMany()
                        .HasForeignKey("OtpTypeId")
                        .HasConstraintName("fk_user_otp_type_otp_type_id");

                    b.Navigation("OtpType");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Auth.PasswordHistory", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthUser", "User")
                        .WithMany("PasswordHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_history_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Auth.UserRefreshToken", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_refresh_token_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Mbr.Member", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Org.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_member_departments_department_id");

                    b.HasOne("Skillitory.Api.DataStore.Entities.Org.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("fk_member_organizations_organization_id");

                    b.HasOne("Skillitory.Api.DataStore.Entities.Mbr.Member", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .HasConstraintName("fk_member_member_supervisor_id");

                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthUser", "User")
                        .WithOne("Member")
                        .HasForeignKey("Skillitory.Api.DataStore.Entities.Mbr.Member", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_user_user_id");

                    b.Navigation("Department");

                    b.Navigation("Organization");

                    b.Navigation("Supervisor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Org.Department", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthUser", "CreationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_department_user_created_by");

                    b.HasOne("Skillitory.Api.DataStore.Entities.Org.Organization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_department_organizations_organization_id");

                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthUser", "UpdatingUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("fk_department_user_updated_by");

                    b.Navigation("CreationUser");

                    b.Navigation("Organization");

                    b.Navigation("UpdatingUser");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Org.Organization", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthUser", "CreationUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_user_created_by");

                    b.HasOne("Skillitory.Api.DataStore.Entities.Auth.AuthUser", "UpdatingUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("fk_organization_user_updated_by");

                    b.Navigation("CreationUser");

                    b.Navigation("UpdatingUser");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Org.OrganizationChurn", b =>
                {
                    b.HasOne("Skillitory.Api.DataStore.Entities.Org.OrganizationChurnCategory", "OrganizationChurnCategory")
                        .WithMany()
                        .HasForeignKey("OrganizationChurnCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_churn_organization_churn_category_organization");

                    b.HasOne("Skillitory.Api.DataStore.Entities.Org.Organization", "Organization")
                        .WithMany("OrganizationChurns")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_churn_organizations_organization_id");

                    b.Navigation("Organization");

                    b.Navigation("OrganizationChurnCategory");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Auth.AuthUser", b =>
                {
                    b.Navigation("Member");

                    b.Navigation("PasswordHistories");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Skillitory.Api.DataStore.Entities.Org.Organization", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("OrganizationChurns");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
